### ISSUE TITLE
`read32` seems to ignore argument `d`

### ISSUE THREAD

**Issue by fratrik** [adafruit/Adafruit_HDC1000_Library#3]
It seems to have a hardcoded value of `50` instead. Is that intentional? See https://github.com/adafruit/Adafruit_HDC1000_Library/blob/master/Adafruit_HDC1000.cpp#L93

**Comment by danesparza** [comment]
@fratrik After a few commits, it looks like this line has moved around.  I think the line you're looking for is [located here](https://github.com/adafruit/Adafruit_HDC1000_Library/blob/master/Adafruit_HDC1000.cpp#L115).  To be clear, it reads:

`uint32_t Adafruit_HDC1000::read32(uint8_t a, uint8_t d)`

The delay with the hardcoded value appears to be [located here](https://github.com/adafruit/Adafruit_HDC1000_Library/blob/master/Adafruit_HDC1000.cpp#L119).

**Comment by ladyada** [comment]
fixed
