### ISSUE TITLE
The function writeConfig() has a double Wire.beginTransmission()

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_HDC1000_Library#4]
The function writeConfig() has two consecutive Wire.beginTransmission() calls. I think the first one will be ignored. That means that I2C address 0x02 will be used, and since there is nothing at 0x02, there will be no ACK, and the I2C transmission is stopped.

**Comment by liyuyao001** [comment]
YES, I tested it today, finding the I2C sending 0x02 as 7 bit slave address, the correction should be made using Wire.write() instead.
Also, the header file should add  guards to avoid "redefinition of class" error.
See attached zip file.

[Adafruit_HDC1000_Library.zip](https://github.com/adafruit/Adafruit_HDC1000_Library/files/1121162/Adafruit_HDC1000_Library.zip)

**Comment by ladyada** [comment]
fixed
